import { HumanMessage, SystemMessage } from '@langchain/core/messages';
import createGroqModel from '../services/groqService.js';

const SYSTEM_PROMPT = `You are a senior tech lead summarizing a Pull Request review.
You will receive outputs from 3 specialized review agents: code quality, security, and dependency.
Your job is to combine them into one clean, structured GitHub PR comment in markdown.

Follow this exact format:

## Automated PR Review

### Summary
| Check | Severity | Issues |
|-------|----------|--------|
| Code Quality | [severity] | [n] issues |
| Security | [severity] | [n] issues |
| Dependencies | [severity] | [n] issues |

### Code Quality
[paste key findings from code quality agent, 2-4 bullet points max]

### Security
[paste key findings from security agent, 2-4 bullet points max]

### Dependencies
[paste key findings from dependency agent, 2-4 bullet points max]

### Verdict
[ONE sentence: merge recommendation — safe to merge / needs minor fixes / do not merge]

---
*Review generated by PR Review Agent*

Keep it concise. Do not use emojis anywhere. Do not repeat the same finding twice.
Use the agent outputs as-is where possible.`;


const runSummarizerAgent = async (agentResults) => {
  const start = Date.now();
  const model = createGroqModel(0.3);

  const codeQuality = agentResults.find((r) => r.agent_name === 'code_quality');
  const security = agentResults.find((r) => r.agent_name === 'security');
  const dependency = agentResults.find((r) => r.agent_name === 'dependency');

  const userMessage = `
CODE QUALITY AGENT OUTPUT:
${codeQuality?.output ?? 'Agent failed to run'}

SECURITY AGENT OUTPUT:
${security?.output ?? 'Agent failed to run'}

DEPENDENCY AGENT OUTPUT:
${dependency?.output ?? 'Agent failed to run'}
`;

  try {
    const response = await model.invoke([
      new SystemMessage(SYSTEM_PROMPT),
      new HumanMessage(userMessage),
    ]);

    return {
      agent_name: 'summarizer',
      output: response.content,
      input_tokens: response.usage_metadata?.input_tokens ?? null,
      output_tokens: response.usage_metadata?.output_tokens ?? null,
      execution_time_ms: Date.now() - start,
      status: 'success',
      error_message: null,
    };
  } catch (error) {
    return {
      agent_name: 'summarizer',
      output: null,
      input_tokens: null,
      output_tokens: null,
      execution_time_ms: Date.now() - start,
      status: 'failed',
      error_message: error.message,
    };
  }
};

export default runSummarizerAgent;