const formatComment = (summaryOutput, prMeta) => {
  if (!summaryOutput) {
    return `## 🤖 Automated PR Review

> ⚠️ Review could not be completed. One or more agents failed to run.

**PR:** ${prMeta.pr_title}
**Author:** ${prMeta.pr_author}

---
*Review generated by PR Review Agent*`;
  }

  return summaryOutput;
};

export default formatComment;